apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysqldb
subsets:
  - addresses:
      - ip: 35.227.117.131
    ports:
      - port: 3306
