apiVersion: v1
kind: Service
metadata:
  name: duqbe
  annotations:
    networking.gke.io/load-balancer-type: 'Internal'
  labels:
    app: duqbe
spec:
  type: LoadBalancer
  selector:
    app: duqbe
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
